BUGFIX/MINOR(zookeeper): Adapt packages to python3  ##### SUMMARY
`19.10` requires python3.
In the future release the `python-zookeeper` package will target `python3-zookeeper`

 ##### IMPACT
N/A

 ##### ADDITIONAL INFORMATION
```
ModuleNotFoundError: No module named 'zookeeper'
```